package org.rao.kotlin.designpatterns.chain.handler

object Constants {
    val PERSON_AUDIT_MESSAGE = "Person identity audit data"
    val PERSON_READ_EVENT_CODE = "P1000030"
    val PERSON_CREATE_EVENT_CODE = "P1000031"
    val PERSON_UPDATE_EVENT_CODE = "P1000032"
    val PERSON_DELETE_EVENT_CODE = "P1000033"

    val PERSON_READ_EVENT_DISPLAYNAME = "READ PERSON"
    val PERSON_CREATE_EVENT_DISPLAYNAME = "CREATE PERSON"
    val PERSON_UPDATE_EVENT_DISPLAYNAME = "UPDATE PERSON"
    val PERSON_DELETE_EVENT_DISPLAYNAME = "DELETE PERSON"


    val ORGANIZATION_AUDIT_MESSAGE = "Organization identity audit data"
    val ORGANIZATION_READ_EVENT_CODE = "O1000010"
    val ORGANIZATION_CREATE_EVENT_CODE = "O1000011"
    val ORGANIZATION_UPDATE_EVENT_CODE = "O1000012"
    val ORGANIZATION_DELETE_EVENT_CODE = "O1000013"

    val ORGANIZATION_READ_EVENT_DISPLAYNAME = "READ ORGANIZATION"
    val ORGANIZATION_CREATE_EVENT_DISPLAYNAME = "CREATE ORGANIZATION"
    val ORGANIZATION_UPDATE_EVENT_DISPLAYNAME = "UPDATE ORGANIZATION"
    val ORGANIZATION_DELETE_EVENT_DISPLAYNAME = "DELETE ORGANIZATION"


    val GROUP_AUDIT_MESSAGE = "Group identity audit data"
    val GROUP_READ_EVENT_CODE = "G1000020"
    val GROUP_CREATE_EVENT_CODE = "G1000021"
    val GROUP_UPDATE_EVENT_CODE = "G1000022"
    val GROUP_DELETE_EVENT_CODE = "G1000023"

    val GROUP_READ_EVENT_DISPLAYNAME = "READ GROUP"
    val GROUP_CREATE_EVENT_DISPLAYNAME = "CREATE GROUP"
    val GROUP_UPDATE_EVENT_DISPLAYNAME = "UPDATE GROUP"
    val GROUP_DELETE_EVENT_DISPLAYNAME = "DELETE GROUP"


    val DEVICE_AUDIT_MESSAGE = "Device identity audit data"
    val DEVICE_READ_EVENT_CODE = "D1000040"
    val DEVICE_CREATE_EVENT_CODE = "D1000041"
    val DEVICE_UPDATE_EVENT_CODE = "D1000042"
    val DEVICE_DELETE_EVENT_CODE = "D1000043"

    val DEVICE_READ_EVENT_DISPLAYNAME = "READ DEVICE"
    val DEVICE_CREATE_EVENT_DISPLAYNAME = "CREATE DEVICE"
    val DEVICE_UPDATE_EVENT_DISPLAYNAME = "UPDATE DEVICE"
    val DEVICE_DELETE_EVENT_DISPLAYNAME = "DELETE DEVICE"

    val UNKNOWN_IDENTITY_TYPE_MESSAGE = "A request made with a unknown identity type"
    val UNKNOWN_IDENTITY_TYPE = "NA"

}
